name: Update Project Issue Status on PR

on:
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  update-project-issue-status:
    runs-on: ubuntu-latest
    steps:
    - name: Update Issue Project Status
      run: |
        PR_BRANCH="${{ github.event.pull_request.head.ref }}"
        OWNER="${{ github.repository_owner }}"
        REPO="${{ github.event.repository.name }}"
        GITHUB_TOKEN="${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        
        # Install dependencies (e.g., jq for parsing JSON)
        sudo apt-get install jq
        
        # List all issues and search for the linked branch
        ISSUES=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
                      "https://api.github.com/repos/$OWNER/$REPO/issues?state=all&per_page=100")
        ISSUE_NUMBER=$(echo $ISSUES | jq -r --arg PR_BRANCH "$PR_BRANCH" '.[] | select(.body | contains($PR_BRANCH)) | .number')
        
        if [ ! -z "$ISSUE_NUMBER" ]; then
          echo "Linked Issue Found: $ISSUE_NUMBER"
          
          # Here you need to add the code to update the issue's status in the GitHub Project.
          # This part depends on the version of GitHub Projects you are using and might require using the GitHub GraphQL API.
          
          # Example GraphQL query to move an item to a different column:
          # query {
          #   mutation {
          #     updateProjectNextItemField() {
          #       //...
          #     }
          #   }
          # }
          
        else
          echo "No linked issue found for branch: $PR_BRANCH"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
