name: Echo Source Branch and Find Linked Issues

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - dev

jobs:
  display-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Source Branch and Find Linked Issues
        run: |
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          REPO="${{ github.repository }}"
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
          echo "This is the source branch: $PR_BRANCH"
          echo "Going to find the issues which link this branch..."
          
          # List all issues and search for the linked branch
          ISSUES=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
                        -X GET "https://api.github.com/repos/$REPO/issues?state=all&per_page=100")
          ISSUE_NUMBERS=$(echo $ISSUES | jq -r --arg PR_BRANCH "$PR_BRANCH" '.[] | select(.body | contains($PR_BRANCH)) | .number')
          
          if [ ! -z "$ISSUE_NUMBERS" ]; then
            echo "Linked Issues Found:"
            echo "$ISSUE_NUMBERS"
          else
            echo "No linked issues found for branch: $PR_BRANCH"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
